/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import Modele.FormatFichierException;
import Modele.Outils;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author heloise
 */
public class GestionMission extends javax.swing.JFrame {
    protected Map<Integer,Modele.Mission> missions;
    /**
     * Creates new form GestionMission
     */
    public GestionMission(Map<Integer,Modele.Mission> missions) {
        initComponents();
        this.missions = missions;
        ArrayList<String> strings = new ArrayList<>();
        for(int mission : missions.keySet()) {
            strings.add("Mission n°" + mission);
        }
        listeMission.setModel(new javax.swing.AbstractListModel<String>() {
            String[] elements = strings.toArray(new String[strings.size()]);
            public int getSize() { return elements.length; }
            public String getElementAt(int i) { return elements[i]; }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exportFic = new javax.swing.JFileChooser();
        pBandeau = new javax.swing.JPanel();
        l_titre = new javax.swing.JLabel();
        bRetour = new javax.swing.JButton();
        pPage = new javax.swing.JPanel();
        bAjoutMission = new javax.swing.JButton();
        bExportFic = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pListe = new javax.swing.JScrollPane();
        listeMission = new javax.swing.JList<>();
        pInfosOnglets = new javax.swing.JTabbedPane();
        ongletInfo = new javax.swing.JPanel();
        l_idM = new javax.swing.JLabel();
        l_dateDeb = new javax.swing.JLabel();
        l_duree = new javax.swing.JLabel();
        l_statut = new javax.swing.JLabel();
        l_valueID = new javax.swing.JLabel();
        l_valueStatut = new javax.swing.JLabel();
        l_valueDateDeb = new javax.swing.JLabel();
        l_valueDuree = new javax.swing.JLabel();
        pStatut = new JPanel();
        ongletComp = new javax.swing.JPanel();
        pComp = new javax.swing.JScrollPane();
        listeComp = new javax.swing.JList<>();
        ongletEmp = new javax.swing.JPanel();
        pComp1 = new javax.swing.JScrollPane();
        listeEmp = new javax.swing.JList<>();
        lTitreListe = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuAccueil = new javax.swing.JMenu();
        menuEmploye = new javax.swing.JMenu();
        itemAllEmp = new javax.swing.JMenuItem();
        itemNewEmp = new javax.swing.JMenuItem();
        menuMission = new javax.swing.JMenu();
        itemAllMission = new javax.swing.JMenuItem();
        itemNewMission = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pBandeau.setBackground(new java.awt.Color(60, 132, 208));
        pBandeau.setPreferredSize(new java.awt.Dimension(317, 73));

        l_titre.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        l_titre.setText("Gestion des missions");

        bRetour.setText("<");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBandeauLayout = new javax.swing.GroupLayout(pBandeau);
        pBandeau.setLayout(pBandeauLayout);
        pBandeauLayout.setHorizontalGroup(
            pBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBandeauLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(bRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(l_titre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBandeauLayout.setVerticalGroup(
            pBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBandeauLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bRetour)
                    .addComponent(l_titre))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pPage.setBackground(new java.awt.Color(255, 255, 255));

        bAjoutMission.setText("Ajouter une mission");
        bAjoutMission.setEnabled(false);
        bAjoutMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjoutMissionActionPerformed(evt);
            }
        });

        bExportFic.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        bExportFic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/img/sauvegarder.jpeg"))); // NOI18N
        bExportFic.setText("Exporter les fiches");
        bExportFic.setToolTipText("");
        bExportFic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportFicActionPerformed(evt);
            }
        });

        listeMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeMissionMouseClicked(evt);
            }
        });
        pListe.setViewportView(listeMission);

        pInfosOnglets.setBackground(new java.awt.Color(255, 255, 255));

        ongletInfo.setBackground(new java.awt.Color(255, 255, 255));

        l_idM.setText("Identifiant de la mission :");

        l_dateDeb.setText("Date de lancement :");

        l_duree.setText("Durée :");

        l_statut.setText("Statut :");

        l_valueID.setToolTipText("");

        l_valueStatut.setToolTipText("");

        pStatut.setBackground(new java.awt.Color(255, 255, 255));
        pStatut.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout pStatutLayout = new javax.swing.GroupLayout(pStatut);
        pStatut.setLayout(pStatutLayout);
        pStatutLayout.setHorizontalGroup(
            pStatutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pStatutLayout.setVerticalGroup(
            pStatutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ongletInfoLayout = new javax.swing.GroupLayout(ongletInfo);
        ongletInfo.setLayout(ongletInfoLayout);
        ongletInfoLayout.setHorizontalGroup(
            ongletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ongletInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ongletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ongletInfoLayout.createSequentialGroup()
                        .addComponent(l_dateDeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_valueDateDeb))
                    .addGroup(ongletInfoLayout.createSequentialGroup()
                        .addComponent(l_duree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_valueDuree))
                    .addGroup(ongletInfoLayout.createSequentialGroup()
                        .addComponent(l_idM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_valueID))
                    .addGroup(ongletInfoLayout.createSequentialGroup()
                        .addComponent(l_statut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_valueStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        ongletInfoLayout.setVerticalGroup(
            ongletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletInfoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ongletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_idM)
                    .addComponent(l_valueID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ongletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_valueDateDeb)
                    .addComponent(l_dateDeb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ongletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_duree)
                    .addComponent(l_valueDuree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ongletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ongletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pStatut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_valueStatut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(l_statut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pInfosOnglets.addTab("Informations", ongletInfo);

        ongletComp.setBackground(new java.awt.Color(255, 255, 255));

        pComp.setViewportView(listeComp);

        javax.swing.GroupLayout ongletCompLayout = new javax.swing.GroupLayout(ongletComp);
        ongletComp.setLayout(ongletCompLayout);
        ongletCompLayout.setHorizontalGroup(
            ongletCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pComp, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ongletCompLayout.setVerticalGroup(
            ongletCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pComp, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        pInfosOnglets.addTab("Compétences", ongletComp);

        ongletEmp.setBackground(new java.awt.Color(255, 255, 255));

        pComp1.setViewportView(listeEmp);

        javax.swing.GroupLayout ongletEmpLayout = new javax.swing.GroupLayout(ongletEmp);
        ongletEmp.setLayout(ongletEmpLayout);
        ongletEmpLayout.setHorizontalGroup(
            ongletEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pComp1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );
        ongletEmpLayout.setVerticalGroup(
            ongletEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pComp1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        pInfosOnglets.addTab("Employés", ongletEmp);

        lTitreListe.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        lTitreListe.setText("Liste des missions");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pListe, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitreListe, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(pInfosOnglets, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pInfosOnglets, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lTitreListe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pListe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pInfosOnglets.getAccessibleContext().setAccessibleName("infos");

        javax.swing.GroupLayout pPageLayout = new javax.swing.GroupLayout(pPage);
        pPage.setLayout(pPageLayout);
        pPageLayout.setHorizontalGroup(
            pPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPageLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bAjoutMission)
                .addGap(18, 18, 18)
                .addComponent(bExportFic, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(pPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pPageLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pPageLayout.setVerticalGroup(
            pPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPageLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAjoutMission, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExportFic, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(pPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPageLayout.createSequentialGroup()
                    .addGap(0, 70, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        menuAccueil.setText("Accueil");
        menuAccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAccueilMouseClicked(evt);
            }
        });
        menu.add(menuAccueil);

        menuEmploye.setText("Employés");

        itemAllEmp.setText("Liste des employés");
        itemAllEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAllEmpActionPerformed(evt);
            }
        });
        menuEmploye.add(itemAllEmp);

        itemNewEmp.setEnabled(false);
        itemNewEmp.setText("Nouvel employé");
        menuEmploye.add(itemNewEmp);

        menu.add(menuEmploye);

        menuMission.setText("Missions");

        itemAllMission.setText("Liste des missions");
        itemAllMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAllMissionActionPerformed(evt);
            }
        });
        menuMission.add(itemAllMission);

        itemNewMission.setEnabled(false);
        itemNewMission.setText("Nouvelle mission");
        menuMission.add(itemNewMission);

        menu.add(menuMission);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBandeau, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addComponent(pPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pBandeau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        new Accueil().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bRetourActionPerformed

    private void listeMissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeMissionMouseClicked
        // onglet informations
        String mission = listeMission.getSelectedValue();
        int idMission = Integer.valueOf(mission.split("°")[1].trim());
        
        Modele.Mission m = Modele.Entreprise.getMission(idMission);
        String idM = Integer.toString(idMission);
        Date dateDeb = m.getDateDebut();
        String duree = Integer.toString(m.getDuree());
        String statut = m.getStatut();
        l_valueID.setText(idM);
        l_valueDuree.setText(duree + " jour(s)");
        l_valueDateDeb.setText(Modele.Outils.sdf.format(dateDeb));
        l_valueStatut.setText(statut);
        Color color = m.getColorStatut();
        pStatut.setBackground(color);
        // onglet competences
        ArrayList<String> compPersMission = new ArrayList<>();
        for(Modele.Competence comp : m.getBesoins().getMapBesoins().keySet()) {
            compPersMission.add(comp.toString());
        }
        listeComp.setModel(new javax.swing.AbstractListModel<String>() {
            String[] elements = compPersMission.toArray(new String[compPersMission.size()]);
            public int getSize() { return elements.length; }
            public String getElementAt(int i) { return elements[i]; }
        });
        // onglet Employés 
        Set<String> persSurMission = new TreeSet<>();
        /*for(String pers : m.getCompPers()) {
            String[] extract = pers.split("-");
            String personne = extract[0];
            String comp = extract[1].replace("_", ", ");
            persSurMission.add(personne + " (" + comp + ")");
        }*/
        for(Modele.Competence comp : m.getAffectations().keySet()) {
            for(int i=0; i<m.getAffectations().get(comp).size(); i++ ){
                if(persSurMission.contains(m.getAffectations().get(comp).get(i).toString())==false){
                    persSurMission.add(m.getAffectations().get(comp).get(i).getNom() + " " + m.getAffectations().get(comp).get(i).getPrenom());
                }
            }
        }
        listeEmp.setModel(new javax.swing.AbstractListModel<String>() {
            String[] elements = persSurMission.toArray(new String[persSurMission.size()]);
            public int getSize() { return elements.length; }
            public String getElementAt(int i) { return elements[i]; }
        });
         
    }//GEN-LAST:event_listeMissionMouseClicked

    private void bAjoutMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjoutMissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAjoutMissionActionPerformed

    private void bExportFicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportFicActionPerformed
        // TODO add your handling code here:
        int returnVal = exportFic.showSaveDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File f = exportFic.getSelectedFile();
            try {
                Outils.sauvegarderMission(f.toString());
            }
            catch (FormatFichierException ef) {
                JOptionPane.showMessageDialog(rootPane, ef.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            catch(IOException ioe) {
                Logger.getLogger(GestionPersonnel.class.getName()).log(Level.SEVERE, null, ioe);
            }
        }
        else {
            System.out.println("File access cancel by user");
        }
    }//GEN-LAST:event_bExportFicActionPerformed

    private void menuAccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAccueilMouseClicked
        new Accueil().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuAccueilMouseClicked

    private void itemAllEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAllEmpActionPerformed
        // TODO add your handling code here:
        new GestionPersonnel(Modele.Entreprise.personnels).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemAllEmpActionPerformed

    private void itemAllMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAllMissionActionPerformed
        // TODO add your handling code here:
        new GestionMission(Modele.Entreprise.missions).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemAllMissionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionMission(Modele.Entreprise.missions).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAjoutMission;
    private javax.swing.JButton bExportFic;
    private javax.swing.JButton bRetour;
    private javax.swing.JFileChooser exportFic;
    private javax.swing.JMenuItem itemAllEmp;
    private javax.swing.JMenuItem itemAllMission;
    private javax.swing.JMenuItem itemNewEmp;
    private javax.swing.JMenuItem itemNewMission;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lTitreListe;
    private javax.swing.JLabel l_dateDeb;
    private javax.swing.JLabel l_duree;
    private javax.swing.JLabel l_idM;
    private javax.swing.JLabel l_statut;
    private javax.swing.JLabel l_titre;
    private javax.swing.JLabel l_valueDateDeb;
    private javax.swing.JLabel l_valueDuree;
    private javax.swing.JLabel l_valueID;
    private javax.swing.JLabel l_valueStatut;
    private javax.swing.JList<String> listeComp;
    private javax.swing.JList<String> listeEmp;
    private javax.swing.JList<String> listeMission;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAccueil;
    private javax.swing.JMenu menuEmploye;
    private javax.swing.JMenu menuMission;
    private javax.swing.JPanel ongletComp;
    private javax.swing.JPanel ongletEmp;
    private javax.swing.JPanel ongletInfo;
    private javax.swing.JPanel pBandeau;
    private javax.swing.JScrollPane pComp;
    private javax.swing.JScrollPane pComp1;
    private javax.swing.JTabbedPane pInfosOnglets;
    private javax.swing.JScrollPane pListe;
    private javax.swing.JPanel pPage;
    private javax.swing.JPanel pStatut;
    // End of variables declaration//GEN-END:variables
}
